### ISSUE TITLE
QuantityPicker Buttons Location

### ISSUE THREAD

**Issue by ngwutadesmond** [andanhm/QuantityPicker#1]
You've built something really great, but something is missing, I am using this library in a project and when user gets to the page where they need the quantity picker it pisses em off because the "+" button is on the Right while the "-" button is on the left. is there something you can do about this?

**Comment by andanhm** [comment]
Thank you for the PR. I am closing this as you had given a fix for the same

**Comment by ngwutadesmond** [comment]
You're welcome

**Comment by ngwutadesmond** [comment]
One more thing, the changes are not reflecting yet. is there anything you need to do?
